from django.urls import path

from . import views

app_name = 'crm'

urlpatterns = [
    path('', views.home, name='home'),
    path('participadas/', views.companies, name='companies'),
    path('participadas/nueva/', views.company_create, name='company_create'),
    path('participadas/<int:pk>/', views.company_detail, name='company_detail'),
    path('participadas/<int:pk>/editar/', views.company_edit, name='company_edit'),
    path('participadas/<int:pk>/eliminar/', views.company_delete, name='company_delete'),
    path('participadas/<int:pk>/set-field/', views.company_set_field, name='company_set_field'),
    path('participadas/<int:company_pk>/rondas/nueva/', views.round_create, name='round_create'),
    path('rondas/<int:pk>/', views.round_detail, name='round_detail'),
    path('rondas/<int:pk>/editar/', views.round_edit, name='round_edit'),
    path('rondas/<int:pk>/eliminar/', views.round_delete, name='round_delete'),
    path('rondas/<int:pk>/set-fase/', views.round_set_fase, name='round_set_fase'),
    path('rondas/fase-log/<int:pk>/upd/', views.round_fase_log_upd, name='round_fase_log_upd'),
    path('rondas/fase-log/<int:pk>/del/', views.round_fase_log_del, name='round_fase_log_del'),
    path('presentaciones/<int:pk>/estado/', views.intro_set_status, name='intro_set_status'),
    path('presentaciones/<int:pk>/editar/', views.intro_edit, name='intro_edit'),
    path('presentaciones/<int:pk>/eliminar/', views.intro_delete, name='intro_delete'),
    path('presentaciones/<int:pk>/cronologia/', views.intro_chrono, name='intro_chrono'),
    path('inversores/', views.investors, name='investors'),
    path('inversores/contactos/', views.investor_contacts, name='investor_contacts'),
    path('inversores/<int:pk>/', views.investor_detail, name='investor_detail'),
    path('inversores/<int:pk>/editar/', views.investor_edit, name='investor_edit'),
    path('inversores/<int:pk>/eliminar/', views.investor_delete, name='investor_delete'),
    path('inversores/<int:pk>/set-field/', views.investor_set_field, name='investor_set_field'),
    path('inversores/<int:pk>/relacion/', views.investor_set_relation, name='investor_set_relation'),
    path('inversores/nuevo/', views.investor_create, name='investor_create'),
    path('inversores/<int:pk>/log/', views.investor_log_create, name='investor_log_create'),
    path('inversores/log/<int:pk>/borrar/', views.investor_log_delete, name='investor_log_delete'),
    path('inversores/interaction/<int:pk>/borrar/', views.interaction_delete, name='interaction_delete'),
    path('inversores/log/<int:pk>/editar/', views.investor_log_edit, name='investor_log_edit'),
    path('inversores/<int:pk>/doc-drop/', views.investor_doc_drop, name='investor_doc_drop'),
    path('contactos/', views.all_contacts, name='all_contacts'),
    path('contactos/editar/', views.contact_edit, name='contact_edit'),
    path('colaboradores/contactos/', views.colaborador_contacts, name='colaborador_contacts'),
    path('colaboradores/<int:pk>/log/', views.colaborador_log_create, name='colaborador_log_create'),
    path('colaboradores/log/<int:pk>/borrar/', views.colaborador_log_delete, name='colaborador_log_delete'),
    path('colaboradores/log/<int:pk>/editar/', views.colaborador_log_edit, name='colaborador_log_edit'),
    path('colaboradores/<int:pk>/doc-drop/', views.colaborador_doc_drop, name='colaborador_doc_drop'),
    path('colaboraciones/log/<int:pk>/borrar/', views.colaboracion_log_delete, name='colaboracion_log_delete'),
    path('presentaciones/pipeline/', views.presentaciones_pipeline, name='presentaciones_pipeline'),
    path('presentaciones/kpis/', views.kpis_inversion, name='kpis_inversion'),
    path('tareas/', views.tareas, name='tareas'),
    path('comunicaciones/', views.comunicaciones, name='comunicaciones'),
    path('presentaciones/', views.presentaciones, name='presentaciones'),
    path('bandeja/', views.inbox, name='inbox'),
    path('bandeja/<int:pk>/borrar/', views.inbox_delete, name='inbox_delete'),
    path('informes/', views.reports, name='reports'),
    # M&A
    path('ma/kpis/', views.kpis_ma, name='kpis_ma'),
    path('ma/', views.procesos_ma_global, name='procesos_ma_global'),
    path('ma/presentaciones/', views.presentaciones_ma, name='presentaciones_ma'),
    path('participadas/<int:company_pk>/ma/nuevo/', views.proceso_ma_create, name='proceso_ma_create'),
    path('ma/<int:pk>/', views.proceso_ma_detail, name='proceso_ma_detail'),
    path('ma/<int:pk>/editar/', views.proceso_ma_edit, name='proceso_ma_edit'),
    path('ma/<int:pk>/eliminar/', views.proceso_ma_delete, name='proceso_ma_delete'),
    path('ma/<int:pk>/set-fase/', views.proceso_ma_set_fase, name='proceso_ma_set_fase'),
    path('ma/fase-log/<int:pk>/upd/', views.proceso_ma_fase_log_upd, name='proceso_ma_fase_log_upd'),
    path('ma/fase-log/<int:pk>/del/', views.proceso_ma_fase_log_del, name='proceso_ma_fase_log_del'),
    path('ma/contacto/<int:pk>/estado/', views.contacto_ma_set_status, name='contacto_ma_set_status'),
    path('ma/contacto/<int:pk>/editar/', views.contacto_ma_edit, name='contacto_ma_edit'),
    path('ma/contacto/<int:pk>/eliminar/', views.contacto_ma_delete, name='contacto_ma_delete'),
    path('ma/contacto/<int:pk>/cronologia/', views.contacto_ma_chrono, name='contacto_ma_chrono'),
    path('compradores/', views.compradores, name='compradores'),
    path('compradores/<int:pk>/', views.comprador_detail, name='comprador_detail'),
    # Colaboraciones
    path('colaboraciones/kpis/', views.kpis_colaboraciones, name='kpis_colaboraciones'),
    path('colaboraciones/', views.colaboraciones_global, name='colaboraciones'),
    path('colaboraciones/pipeline/', views.colaboraciones_pipeline, name='colaboraciones_pipeline'),
    path('colaboraciones/<int:pk>/estado/', views.colaboracion_set_status, name='colaboracion_set_status'),
    path('participadas/<int:company_pk>/colaboraciones/nueva/', views.colaboracion_create, name='colaboracion_create'),
    path('colaboraciones/<int:pk>/', views.colaboracion_detail, name='colaboracion_detail'),
    path('colaboraciones/<int:pk>/editar/', views.colaboracion_edit, name='colaboracion_edit'),
    path('colaboraciones/<int:pk>/eliminar/', views.colaboracion_delete, name='colaboracion_delete'),
    path('colaboraciones/<int:pk>/editar-inline/', views.colaboracion_edit_inline, name='colaboracion_edit_inline'),
    path('colaboraciones/<int:pk>/cronologia/', views.colaboracion_chrono, name='colaboracion_chrono'),
    path('colaboraciones/log/<int:pk>/del/', views.colaboracion_log_del, name='colaboracion_log_del'),
    path('colaboraciones/log/<int:pk>/upd/', views.colaboracion_log_upd, name='colaboracion_log_upd'),
    path('colaboradores/', views.colaboradores, name='colaboradores'),
    path('colaboradores/nuevo/', views.colaborador_create, name='colaborador_create'),
    path('colaboradores/<int:pk>/', views.colaborador_detail, name='colaborador_detail'),
    path('colaboradores/<int:pk>/editar/', views.colaborador_edit, name='colaborador_edit'),
    path('colaboradores/<int:pk>/eliminar/', views.colaborador_delete, name='colaborador_delete'),
    path('colaboradores/<int:pk>/set-field/', views.colaborador_set_field, name='colaborador_set_field'),
    path('colaboradores/<int:pk>/relacion/', views.colaborador_set_relation, name='colaborador_set_relation'),
    path('parse-email/', views.parse_email, name='parse_email'),
    path('parse-contact-email/', views.parse_contact_email, name='parse_contact_email'),
    # Documentación
    path('docs/', views.docs_centro, name='docs_centro'),
    path('docs/empresa/<int:company_pk>/', views.docs_company, name='docs_company'),
    path('docs/empresa/<int:company_pk>/<str:tipo>/<int:ref_pk>/', views.docs_carpeta, name='docs_carpeta'),
    path('docs/borrar/<int:doc_pk>/', views.docs_delete, name='docs_delete'),
    path('docs/contactos/', views.docs_contactos, name='docs_contactos'),
    path('docs/contactos/<str:tipo>/<str:slug>/', views.docs_contactos_carpeta, name='docs_contactos_carpeta'),
    path('docs/contactos/<str:tipo>/<str:slug>/<str:filename>', views.docs_contactos_download, name='docs_contactos_download'),
    # Admin
    path('usuarios/', views.users, name='users'),
    path('ajustes/', views.settings_view, name='settings'),
]
