# Generated by Django 5.2.15 on 2026-06-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('int_code', models.CharField(blank=True, max_length=50, verbose_name='Código interno')),
                ('fund', models.CharField(blank=True, choices=[('BIKF', 'BIKF'), ('BISEF', 'BISEF'), ('BIGINF', 'BIGINF')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Álava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'), ('Almería', 'Almería'), ('Asturias', 'Asturias'), ('Ávila', 'Ávila'), ('Badajoz', 'Badajoz'), ('Baleares', 'Baleares'), ('Barcelona', 'Barcelona'), ('Bizkaia', 'Bizkaia'), ('Burgos', 'Burgos'), ('Cáceres', 'Cáceres'), ('Cádiz', 'Cádiz'), ('Cantabria', 'Cantabria'), ('Castellón', 'Castellón'), ('Ciudad Real', 'Ciudad Real'), ('Córdoba', 'Córdoba'), ('Cuenca', 'Cuenca'), ('Gipuzkoa', 'Gipuzkoa'), ('Girona', 'Girona'), ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Jaén', 'Jaén'), ('La Coruña', 'La Coruña'), ('La Rioja', 'La Rioja'), ('Las Palmas', 'Las Palmas'), ('León', 'León'), ('Lleida', 'Lleida'), ('Lugo', 'Lugo'), ('Madrid', 'Madrid'), ('Málaga', 'Málaga'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('Ourense', 'Ourense'), ('Palencia', 'Palencia'), ('Pontevedra', 'Pontevedra'), ('Salamanca', 'Salamanca'), ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'), ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'), ('Valladolid', 'Valladolid'), ('Zamora', 'Zamora'), ('Zaragoza', 'Zaragoza'), ('Ceuta', 'Ceuta'), ('Melilla', 'Melilla')], max_length=50)),
                ('sectors', models.CharField(blank=True, help_text='Lista separada por comas', max_length=500, verbose_name='Sectores')),
                ('stage', models.CharField(blank=True, choices=[('Pre-seed', 'Pre-seed'), ('Seed', 'Seed'), ('Start-Up', 'Start-Up'), ('Early Stage', 'Early Stage'), ('Venture Capital', 'Venture Capital'), ('Growth', 'Growth')], max_length=50)),
                ('trl', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=20, verbose_name='TRL')),
                ('mrl', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=20, verbose_name='MRL')),
                ('ttm', models.CharField(blank=True, choices=[('UNKNOWN', 'UNKNOWN'), ('> 6 years', '> 6 years'), ('4-6 years', '4-6 years'), ('2-4 years', '2-4 years'), ('1-2 years', '1-2 years'), ('6 months-1 year', '6 months-1 year'), ('Inmediatly', 'Inmediatly'), ('Already on the market', 'Already on the market')], max_length=30, verbose_name='Time to market')),
                ('revenue', models.CharField(blank=True, choices=[('UNKNOWN', 'UNKNOWN'), ('SALES > 10M€', 'SALES > 10M€'), ('4M€ > SALES > 10M€', '4M€ > SALES > 10M€'), ('2M€ > SALES > 5M€', '2M€ > SALES > 5M€'), ('1M€ > SALES > 2M€', '1M€ > SALES > 2M€'), ('500k > SALES > 1M€', '500k > SALES > 1M€'), ('0 > SALES > 500k€', '0 > SALES > 500k€'), ('NO SALES', 'NO SALES')], max_length=30, verbose_name='Facturación')),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valuation_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Participada',
                'verbose_name_plural': 'Participadas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EstadoPresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtapaRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaseRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.company')),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('intro_by', models.CharField(blank=True, max_length=150, verbose_name='Presentado por')),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introductions', to='crm.company')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introductions', to='crm.estadopresentacion')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.introduction')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Other', 'Other'), ('FFF', 'FFF'), ('Business Angel', 'Business Angel'), ('Intermediary', 'Intermediary'), ('Family Office', 'Family Office'), ('Multifamily Office', 'Multifamily Office'), ('Venture Capital', 'Venture Capital'), ('Corporate Venture Capital', 'Corporate Venture Capital'), ('Corporate', 'Corporate'), ('Investment Banking', 'Investment Banking'), ('Patrimonial Banking', 'Patrimonial Banking'), ('Private Banking', 'Private Banking'), ('Banking', 'Banking'), ('Foundation', 'Foundation'), ('Endowments', 'Endowments'), ('Insurance Company', 'Insurance Company'), ('Sovereign Wealth Fund', 'Sovereign Wealth Fund'), ('Pension Fund', 'Pension Fund'), ('Fund of Funds', 'Fund of Funds')], max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('sectors', models.CharField(blank=True, help_text='Lista separada por comas', max_length=500)),
                ('areas', models.CharField(blank=True, help_text='Lista separada por comas', max_length=500)),
                ('inv_stage', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Pre-Seed', 'Pre-Seed'), ('Seed', 'Seed'), ('Pre Series A (VC Early Stage)', 'Pre Series A (VC Early Stage)'), ('Series A (VC)', 'Series A (VC)'), ('Series B (VC Late Stage)', 'Series B (VC Late Stage)'), ('Series C (Growth Capital)', 'Series C (Growth Capital)')], max_length=50, verbose_name='Etapa de inversión')),
                ('ticket_range', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('<200 k€', '<200 k€'), ('200k€ - 500 k€', '200k€ - 500 k€'), ('500k€ - 1M€', '500k€ - 1M€'), ('1M€-2M€', '1M€-2M€'), ('2M€-5M€', '2M€-5M€'), ('5M€-10M€', '5M€-10M€'), ('>10M€', '>10M€')], max_length=30, verbose_name='Rango de ticket')),
                ('aum', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('<500 k€', '<500 k€'), ('500 k€ - 2 M€', '500 k€ - 2 M€'), ('2 M€ - 20 M€', '2 M€ - 20 M€'), ('20 M€ - 50 M€', '20 M€ - 50 M€'), ('50 M€ - 100 M€', '50 M€ - 100 M€'), ('100 M€ - 200 M€', '100 M€ - 200 M€'), ('>200 M€', '>200 M€')], max_length=30, verbose_name='AUM')),
                ('pub_status', models.CharField(blank=True, max_length=100, verbose_name='Estado público')),
                ('notes', models.TextField(blank=True)),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='crm.etaparelacion')),
            ],
            options={
                'verbose_name': 'Inversor',
                'verbose_name_plural': 'Inversores',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='introduction',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introductions', to='crm.investor'),
        ),
        migrations.CreateModel(
            name='InvestorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120, verbose_name='Tipo')),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rstage', models.CharField(blank=True, max_length=50, verbose_name='Etapa de la ronda')),
                ('start', models.DateField(blank=True, null=True)),
                ('close', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='crm.company')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', to='crm.faseronda')),
            ],
            options={
                'verbose_name': 'Ronda',
                'verbose_name_plural': 'Rondas',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='InvestorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.investor')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_logs', to='crm.round')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='introduction',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introductions', to='crm.round'),
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=200)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('unread', models.BooleanField(default=True)),
                ('saved', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_messages', to='crm.investor')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_messages', to='crm.round')),
            ],
            options={
                'verbose_name': 'Mensaje de bandeja',
                'verbose_name_plural': 'Bandeja de entrada',
                'ordering': ['-date'],
            },
        ),
    ]
