# Generated by Django 5.2.15 on 2026-06-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('type', models.CharField(blank=True, choices=[('Cliente potencial', 'Cliente potencial'), ('Proveedor potencial', 'Proveedor potencial'), ('Partner tecnológico', 'Partner tecnológico'), ('Partner comercial', 'Partner comercial'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('sectors', models.CharField(blank=True, max_length=500, verbose_name='Sectores')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EstadoColaboracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColaboradorContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('type', models.CharField(blank=True, choices=[('Estratégico', 'Estratégico'), ('Private Equity', 'Private Equity'), ('Family Office', 'Family Office'), ('Fondo de Inversión', 'Fondo de Inversión'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('sectors', models.CharField(blank=True, max_length=500, verbose_name='Sectores')),
                ('notes', models.TextField(blank=True)),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compradores', to='crm.etaparelacion')),
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompradorContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Colaboracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(blank=True, choices=[('Cliente potencial', 'Cliente potencial'), ('Proveedor potencial', 'Proveedor potencial'), ('Partner tecnológico', 'Partner tecnológico'), ('Partner comercial', 'Partner comercial'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo de relación')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('intro_by', models.CharField(blank=True, max_length=150, verbose_name='Presentado por')),
                ('next_action', models.CharField(blank=True, max_length=255, verbose_name='Próximo paso')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Fecha próximo paso')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboraciones', to='crm.company')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboraciones', to='crm.colaborador')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboraciones', to='crm.estadocolaboracion')),
            ],
            options={
                'verbose_name': 'Colaboración',
                'verbose_name_plural': 'Colaboraciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContactoMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Oferta (€)')),
                ('nda_firmado', models.BooleanField(default=False, verbose_name='NDA firmado')),
                ('dd_iniciado', models.BooleanField(default=False, verbose_name='DD iniciada')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha contacto')),
                ('intro_by', models.CharField(blank=True, max_length=150, verbose_name='Presentado por')),
                ('next_action', models.CharField(blank=True, max_length=255, verbose_name='Próximo paso')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Fecha próximo paso')),
                ('notes', models.TextField(blank=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_ma', to='crm.comprador')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='crm.estadoma')),
            ],
            options={
                'verbose_name': 'Contacto M&A',
                'verbose_name_plural': 'Contactos M&A',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionColaboracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('colaboracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.colaboracion')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.contactoma')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del proceso')),
                ('precio_pedido', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Precio pedido (€)')),
                ('cerrado', models.BooleanField(default=False, verbose_name='Proceso cerrado')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Inicio')),
                ('close', models.DateField(blank=True, null=True, verbose_name='Cierre estimado')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_ma', to='crm.company')),
            ],
            options={
                'verbose_name': 'Proceso M&A',
                'verbose_name_plural': 'Procesos M&A',
                'ordering': ['-start'],
            },
        ),
        migrations.AddField(
            model_name='contactoma',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='crm.procesoma'),
        ),
    ]
