# Generated by Django 5.2.15 on 2026-06-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_mixed_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='procesoma',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos', to='crm.fasema'),
        ),
    ]
