# Generated by Django 5.2.15 on 2026-06-23 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_fase_ma'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE crm_colaborador SET relation_id = NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='EtapaRelacionColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'id'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='crm.etaparelacioncolaborador'),
        ),
    ]
