# Generated by Django 5.2.15 on 2026-06-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_etapa_relacion_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorlog',
            name='created_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
