# Generated by Django 5.2.15 on 2026-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_investorlog_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='es_inversor_esporadico',
            field=models.BooleanField(default=False, verbose_name='Inversor esporádico'),
        ),
    ]
