# Generated by Django 5.2.15 on 2026-06-23 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_inversor_esporadico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.colaborador')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
