# Generated by Django 5.2.15 on 2026-06-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_colaborador_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='inv_stage',
            field=models.CharField(blank=True, max_length=500, verbose_name='Etapa de inversión'),
        ),
    ]
