# Generated by Django 5.2.15 on 2026-06-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_inv_stage_multivalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='tipo_inversion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de inversión'),
        ),
    ]
