# Generated by Django 5.2.15 on 2026-06-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_docs_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
    ]
