# Generated by Django 5.2.15 on 2026-06-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='carpeta',
            field=models.CharField(
                choices=[
                    ('general',   'General'),
                    ('emails',    'Emails'),
                    ('reuniones', 'Reuniones'),
                    ('notas',     'Notas'),
                ],
                default='general',
                max_length=20,
            ),
        ),
    ]
