# Generated by Django 5.2.15 on 2026-06-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_carpeta_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorlog',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='investorlog',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
