# Generated by Django 5.2.15 on 2026-06-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_attachment_url_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorlog',
            name='context',
            field=models.CharField(blank=True, choices=[('', 'General'), ('ronda', 'Ronda de Inversión'), ('ma', 'Proceso M&A'), ('colaboracion', 'Colaboración')], max_length=20),
        ),
        migrations.AddField(
            model_name='investorlog',
            name='context',
            field=models.CharField(blank=True, choices=[('', 'General'), ('ronda', 'Ronda de Inversión'), ('ma', 'Proceso M&A'), ('colaboracion', 'Colaboración')], max_length=20),
        ),
    ]
