# Generated by Django 5.2.15 on 2026-06-25 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_log_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorlog',
            name='colaboracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_logs', to='crm.colaboracion'),
        ),
        migrations.AddField(
            model_name='colaboradorlog',
            name='proceso_ma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_logs', to='crm.procesoma'),
        ),
        migrations.AddField(
            model_name='colaboradorlog',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador_logs', to='crm.round'),
        ),
        migrations.AddField(
            model_name='investorlog',
            name='colaboracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_logs', to='crm.colaboracion'),
        ),
        migrations.AddField(
            model_name='investorlog',
            name='proceso_ma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_logs', to='crm.procesoma'),
        ),
    ]
