# Generated by Django 5.2.15 on 2026-06-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_log_process_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboracion',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='round',
            name='rstage',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Pre-Seed', 'Pre-Seed'), ('Seed', 'Seed'), ('Pre Series A (VC Early Stage)', 'Pre Series A (VC Early Stage)'), ('Series A (VC)', 'Series A (VC)'), ('Series B (VC Late Stage)', 'Series B (VC Late Stage)'), ('Series C (Growth Capital)', 'Series C (Growth Capital)')], max_length=50, verbose_name='Etapa de la ronda'),
        ),
    ]
