# Generated by Django 5.2.15 on 2026-06-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_descripcion_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoMAFaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('fase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proceso_logs', to='crm.fasema')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fase_logs', to='crm.procesoma')),
            ],
            options={
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RoundFaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('fase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_logs', to='crm.faseronda')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fase_logs', to='crm.round')),
            ],
            options={
                'ordering': ['date', 'pk'],
            },
        ),
    ]
