# Generated by Django 5.2.15 on 2026-07-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_catalogo_habilitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='investor',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
