# Generated by Django 5.2.15 on 2026-07-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_add_website_phone_linkedin_to_investor_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
