# Generated by Django 5.2.15 on 2026-07-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_add_website_phone_linkedin_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
    ]
