# Generated by Django 5.2.15 on 2026-07-07 13:28

from django.db import migrations, models


def seed(apps, schema_editor):
    TipoInversion = apps.get_model('crm', 'TipoInversionInversor')
    for i, nombre in enumerate(['Inversión Directa', 'Partícipe de Fondos (LP)', 'Desconocido']):
        TipoInversion.objects.get_or_create(nombre=nombre, defaults={'orden': i})

    EstadoPublico = apps.get_model('crm', 'EstadoPublicoInversor')
    for i, nombre in enumerate(['Privado', 'Público', 'Desconocido']):
        EstadoPublico.objects.get_or_create(nombre=nombre, defaults={'orden': i})


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_remove_tipos_contacto_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPublicoInversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('habilitada', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado público',
                'verbose_name_plural': 'Estados públicos',
                'ordering': ['orden', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoInversionInversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('habilitada', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de inversión',
                'verbose_name_plural': 'Tipos de inversión',
                'ordering': ['orden', 'nombre'],
                'abstract': False,
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
