# Generated by Django 5.2.15 on 2026-07-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_unify_etapa_relacion_grado_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='pub_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado público'),
        ),
    ]
