# Generated by Django 5.2.15 on 2026-07-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_add_missing_fk_columns'),
        ('crm', '0035_add_pub_status_colaborador'),
    ]

    operations = [
    ]
